parameters:
    zobus_bad_request.event_subscriber.bad_request.class: Zorbus\BadRequestBundle\EventListener\BadRequestSubscriber

services:
    zorbus_bad_request.event_subscriber.bad_request:
        class: %zorbus_bad_request.event_subscriber.bad_request.class%
        arguments:
            - @annotation_reader
            - @form.factory
        tags:
            - { name: kernel.event_subscriber }
